### ISSUE TITLE
Greenhouse Effect - Main checklist

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#1]
# Greenhouse Effect master checklist

## Design
- [x] **Sim folder and design doc created** (Date: 12/04/2019)
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [ ] **Legacy sim docs/info gathered**
  - [x] [Sim suggestions doc](https://phet.unfuddle.com/a#/projects/9404/notebooks/3863/pages/105821) reviewed
  - [ ] Unfuddle tickets reviewed ([searching tickets](https://github.com/phetsims/phet-info/blob/master/issue-info/unfuddle-ticket-search.md))
- [x] **Learning goals and standards identified** (Date: 02/04/2020)
- [x] **Design concept complete**  (Date: 05/05/2020)
- [ ] **Wireframes complete** (Date: //) 
- [ ] **Mockups complete** (Date: //) 
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- [ ] **Interviews complete** (Date: //) 
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //) 
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests
- [ ] **Pre-publication items** 
  - [ ] Auxilary screenshots (up to 3 additional)
  - [ ] Screen-specific screenshots for metadata service (see [naming convention](https://github.com/phetsims/website/issues/1322#issuecomment-1010320827))
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Accessibility features
  - [ ] Email announcement language
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Sim primer draft
  - [ ] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [ ] LoL [metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [ ] **Post-publication items** 
  - [ ] Share new features, design challenges, and treats with group!
  - [ ] Review legacy gold star activities, copy over if appropriate
  - [ ] Email announcement language
  - [ ] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [x] **Repository created** (Date: 2/28/2020)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Use `grunt create-sim` in perennial (see `--help` for arguments) to create the repository structure
  - [x] Collaborators added (Developer team, QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [ ] **Development started** (Date: //)
- [ ] **Sim is "feature complete"** (Date: //)
- [ ] **Code review completed** (Date: //)
- [ ] **Pre-publication items**
  - [ ] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))
  - [ ] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks)
  - [ ] Notify MP to manually hide legacy simulation (Java sim lives at `simulations/greenhouse`)
- [ ] **Published** (Date: //)
  - [ ] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [ ] **Legacy sim tested for bugs**; issues reported in repo
- [ ] **Dev testing started** (Date: //)
- [ ] **Dev testing completed** (Date: //)
- [ ] **First RC published** (Date: //)
  - [ ] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [ ] **RC testing completed** (Date: //)

**Comment by jbphet** [comment]
Assigning to @arouinfar the add dates and check boxes for the design items that have been done to date.

**Comment by jbphet** [comment]
I'm going to go ahead and close this.  The phet brand version has been published for a while and the phet-io brand is getting close, and this issue isn't being used to track any of that.
