### ISSUE TITLE
Items for Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#95]
Opening this issue to collect items to document in the Teacher Tips.

- [x] Query Parameters: `defaultTemperatureUnits`, `screens`, `audio`, `supportsPanAndZoom` (check against https://github.com/phetsims/greenhouse-effect/blob/master/js/common/GreenhouseEffectQueryParameters.ts)
- <s>Variations in wave representation due to random selection at startup, #87</s>
- [x] The displayed layer temperatures are null until the first IR photon is absorbed in the view. 
- [x] Haze is a visual indication of greenhouse gas concentration, #115 
- [x] Ratio of IR to visible photons is 5:1, which is not literally accurate but conveys the right idea, #116
- [x] IR photons are roughly normal to the ground when first emitted. This makes it clearer when photons are absorbed/emitted by the atmosphere.
- [ ] Inclusive Features section (use RaP as an example)
- [x] Cloud does not contribute water vapor to GHG concentration. Only models albedo. 
- [x] Cloud is always enabled when exploring by time period so that the temperatures match the real average for those years. #121 
- [x] Energy balance equilibrium vs. surface temperature equilibrium - https://github.com/phetsims/greenhouse-effect/issues/161
- [x] Blackbody spectrum of the sun includes IR, but we do not model it in sim. "Sunlight" = visible.
- [ ] "Surface temperature stable" alert may be .1 degree off, see #137 and #184 
- [x] Wave stroke weight is mapped to intensity #84 
- [x] For best results, wait until the simulation reaches equilibrium before starting a new experiment. For example #193
- [ ] Object responses are scheduled on a 4-second timer, so there may be slight delays. For example, the Energy Balance sound may stop a few seconds before the "equal" object response is said - #203  
- [x] The sim shows the drivers of greenhouse effects, not the effects of climate change. Small changes in the concentration of greenhouse gases can lead to large effects. 
- [x] Water vapor is the most abundant greenhouse gas in the atmosphere, but it is a condensable gas and its concentration depends on the temperature of the atmosphere. This makes water vapor the only greenhouse gas whose concentration increases because the atmosphere is warming, and causes it to warm even more. see https://climate.nasa.gov/ask-nasa-climate/3143/steamy-relationships-how-atmospheric-water-vapor-amplifies-earths-greenhouse-effect/ and #219 
- [x] Minimum surface temperature #249
- [x] Differences in Energy Flux at different greenhouse gas concentrations or time periods will be more noticeable closer to the surface. This is because the density of greenhouse gases in the atmosphere decreases with altitude.

**Comment by arouinfar** [comment]
The prototype is nearing publication, so I should get started on the Teacher Tips. Removing the on-hold label.

**Comment by arouinfar** [comment]
Teacher Tips for 1.1 have been uploaded. The remaining items all pertain to inclusive features, so marking this issue as on-hold again.

**Comment by arouinfar** [comment]
I'd prefer to track Teacher Tips updates in new issues, so let's close this one.
